In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets

In [17]:
iris = datasets.load_iris()
iris_x = iris.data
iris_y = iris.target
print ('Number of classes: %d' %len(np.unique(iris_y)))
print ('Number of data points: %d' %len(iris_y))

X0 = iris_x[iris_y == 0,:]
print ("samples from class 0", X0[:5,:])

X1 = iris_x[iris_y == 1,:]
print ("samples from class 0", X1[:5,:])

X2 = iris_x[iris_y == 0,:]
print ("samples from class 0", X2[:5,:])

Number of classes: 3
Number of data points: 150
samples from class 0 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
samples from class 0 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]
samples from class 0 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris_x, iris_y, test_size=50)

print("Traing size", len(y_train))
print("Test size", len(y_test))

Traing size 100
Test size 50


In [31]:
clf = neighbors.KNeighborsClassifier(n_neighbors = 1, p = 2)
clf.fit(X_train, y_train) #y_train cho biết nhãn tương ứng với mẫu
y_pred = clf.predict(X_test)

print("Print results for 20 test data points: ")
print("Predicted labels: ", y_pred[20:40])
print("Ground truth:     ", y_test[20:40])


Print results for 20 test data points: 
Predicted labels:  [0 0 0 1 1 1 0 1 2 0 1 2 2 2 0 1 0 2 1 1]
Ground truth:      [0 0 0 1 1 1 0 1 2 0 2 2 2 2 0 1 0 2 1 1]


### Đánh giá

In [40]:
# sử dụng hàm accuracy_score
from sklearn.metrics import accuracy_score
print(f"Accuracy of 1KN: {100 * accuracy_score(y_test, y_pred):.2f}%")

Accuracy of 1KN: 96.00%


### Đánh trọng số cho các điểm lân cận 

In [55]:
clf = neighbors.KNeighborsClassifier(n_neighbors = 10, p = 2, weights = 'distance')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print ("Accuracy of 10NN (1/distance weights): %.2f %%" %(100*accuracy_score(y_test, y_pred)))

Accuracy of 10NN (1/distance weights): 96.00 %
